spring.application.name=dogpaws.backend
server.port=8080

#maiadb set
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_USERNAME}
spring.datasource.password=${SPRING_USERPW}

#mybatisconfig
mybatis.mapper-locations=classpath:mapper/**/*.xml
logging.level.org.springframework.security=debug

mybatis.configuration.map-underscore-to-camel-case=true

# MyBatis 로깅 설정 추가
logging.level.com.dogpaws.backend.repository.dao.rim.OrderDao=TRACE
logging.level.org.mybatis=TRACE

mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# mybatis 설정 추가
mybatis.configuration.default-enum-type-handler=org.apache.ibatis.type.EnumTypeHandler
mybatis.type-handlers-package=com.dogpaws.backend.repository.dao.rim
mybatis.type-aliases-package=com.dogpaws.backend.dto.rim


#jpa
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

#JSON?? ?????? ??????? ?? ??
spring.jackson.property-naming-strategy=SNAKE_CASE

#static path set
spring.mvc.static-path-pattern=/static/**

#?? ??? ??
spring.servlet.multipart.location=C:/uploads/

#file
#?? ??? ???
spring.servlet.multipart.enabled=true
#???? ?? ?? ?? 10MB
spring.servlet.multipart.max-file-size=10MB
#HTTP ???? ?? ? ?? ?? ?? 10MB
spring.servlet.multipart.max-request-size=10MB
#??? ??? ????
file.upload-dir=frontend/uploads
#??????? ???? ??? ??? ? ?? URL ??
front.file-dir=http://localhost:2000/uploads/

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

#???????? ????
#???? ??, ?? ?? ??? ??? ?? ? ??
logging.level.jdbc=DEBUG
logging.level.jdbc.sqlonly=DEBUG
logging.level.jdbc.resultset=TRACE
logging.level.jdbc.connection=TRACE
logging.level.jdbc.statement=DEBUG

spring.jwt.secret=${SPRING_JWT_SECRET}

kakao.client-id=${KAKAO_CLIENT_ID}
kakao.redirect-uri=http://localhost:8080/oauth
kakao.token-uri=https://kauth.kakao.com/oauth/token
kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
kakao.logout-uri=https://kauth.kakao.com/oauth/logout
kakao.logout_redirect_uri=http://localhost:2000

naver.client-id=${NAVER_CLIENT_ID}
naver.redirect-uri=http://localhost:8080/naver/callback
naver.naverClientSecret=${NAVER_NAVER_CLIENT_SECRET}

google.client-id=${GOOGLE_CLIENT_ID}
google.client-secret=${GOOGLE_CLIENT_SECRET}
google.redirect-uri=http://localhost:8080/auth/callback

kakao.api.key=${KAKAO_API_KEY}

#fcm
firebase.config.path=backend/src/main/resources/paws2-6ce51-firebase-adminsdk-fbsvc-c5b52c56cf.json

# 스케줄러 로깅 설정 추가
logging.level.com.dogpaws.backend.scheduler=DEBUG
logging.level.com.dogpaws.backend.event=DEBUG
logging.level.com.dogpaws.backend.service.rim.NotificationService=DEBUG